# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Henry Ayres Blog
email: hayres@zeriba.co.uk
description: > # this means to ignore newlines until "baseurl:"
    A blog about sporting activities, life experiences and professional musings of Henry Ayres.
     Recently someone told me I should write a book of my experiences.  Perhaps this is the precursor to that?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henryayres.co.uk" # the base hostname & protocol for your site
twitter_username: hayres
github_username:  hayres
facebook_username:  henryayres
image_url: "/assets/images/"
icon_image_url: "/assets/images/icons/"
# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "node_modules/"
  - "package.json"
  - "Gruntfile.js"


